MovieStore.Web/Models/MovieCartPartialViewModel.cs
using MovieStore.Lib.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MovieStore.Web.Models
{
    public class MovieCartPartialViewModel
    {
        public Movie Movie { get; set; }
        public int Count { get; set; }
        public decimal TotalPrice { get; set; }
    }
}

MovieStore.Web/Controllers/CartController.cs
using MovieStore.Lib.Models;
using MovieStore.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieStore.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CartController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Cart
        public ActionResult Index()
        {
            var movies = Session["CartMovies"];

            return View(movies);
        }

        public ActionResult Remove(int movieId)
        {
            var sessionStorage = (List<Movie>)Session["CartMovies"];

            if (sessionStorage != null && sessionStorage.Count > 0)
            {
                Movie movie = _context.Movies.FirstOrDefault(m => m.Id == movieId);
                sessionStorage.Remove(sessionStorage.LastOrDefault(m => m.Id == movie.Id));

                if (sessionStorage.Count < 1)
                {
                    sessionStorage = null;
                }

                Session["CartMovies"] = sessionStorage;
            }

            return RedirectToAction("Index");
        }

        public ActionResult Add(int movieId)
        {
            Movie movie = _context.Movies.FirstOrDefault(m => m.Id == movieId);
            int count = 0;

            if (movie != null)
            {
                var sessionStorage = (List<Movie>)Session["CartMovies"];

                if (sessionStorage != null && sessionStorage.Count > 0)
                {
                    sessionStorage.Add(movie);
                    count = sessionStorage.Count;
                    Session["CartMovies"] = sessionStorage;
                }
                else
                {
                    sessionStorage = new List<Movie>
                    {
                        movie
                    };
                    count = sessionStorage.Count;
                    Session["CartMovies"] = sessionStorage;
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult RemoveAll()
        {
            Session["CartMovies"] = null;

            return RedirectToAction("Index");
        }

        // POST: Cart/AddToCart
        [HttpPost]
        [ValidateAntiForgeryToken]
        public int AddToCart(int movieId)
        {
            Movie movie = _context.Movies.FirstOrDefault(m => m.Id == movieId);
            int count = 0;

            if (movie != null)
            {
                var sessionStorage = (List<Movie>)Session["CartMovies"];

                if (sessionStorage != null && sessionStorage.Count > 0)
                {
                    sessionStorage.Add(movie);
                    count = sessionStorage.Count;
                    Session["CartMovies"] = sessionStorage;
                }
                else
                {
                    sessionStorage = new List<Movie>
                    {
                        movie
                    };
                    count = sessionStorage.Count;
                    Session["CartMovies"] = sessionStorage;
                }
            }

            return count;
        }
    }
}

MovieStore.Web/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MovieStore.Lib.DataAccess;
using MovieStore.Lib.Models;
using MovieStore.Web.Models;

namespace MovieStore.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        private readonly OMDBDataAccess _movieAccess = new OMDBDataAccess();

        // GET: Movies
        [Authorize]
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                return View(db.Movies.ToList());
            }

            return RedirectToAction("Index", "Home");
        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "NotFound", new { aspxerrorpath = Request.Url.AbsolutePath });
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return RedirectToAction("Index", "NotFound", new { aspxerrorpath = Request.Url.AbsolutePath });
            }
            return View(movie);
        }

        public async Task<ActionResult> DetailsImdb(string id)
        {
            var rnd = new Random();
            var mov = db.Movies.FirstOrDefault(m => m.ImdbID == id);

            if (mov != null)
            {
                return RedirectToAction("Details", new { id = mov.Id });
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                MovieResponse movieRes = await _movieAccess.GetMovieById(id);
                if (movieRes == null)
                {
                    return HttpNotFound();
                }

                Movie movie = new Movie
                {
                    Director = movieRes.Director,
                    Genre = movieRes.Genre,
                    ImdbID = movieRes.imdbID,
                    ImdbRating = movieRes.imdbRating,
                    Plot = movieRes.Plot,
                    Poster = _movieAccess.FixPosterURL(movieRes.Poster),
                    Price = rnd.Next(29, 199),
                    Rated = movieRes.Rated,
                    ReleaseYear = movieRes.Year,
                    Title = movieRes.Title
                };

                db.Movies.Add(movie);
                await db.SaveChangesAsync();

                var mo = db.Movies.FirstOrDefault(m => m.ImdbID == id);

                if (mo != null)
                {
                    return RedirectToAction("Details", new { id = mo.Id });
                }
                else
                {
                    return View(movie);
                }
            }
        }

        // GET: Movies/Create
        [Authorize]
        public ActionResult Create()
        {
            if (User.IsInRole("Admin"))
            {
                return View();
            }

            return RedirectToAction("Index", "Home");
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,Title,Director,ReleaseYear,Price,Rated,Genre,Plot,Poster,ImdbRating,ImdbID")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Title,Director,ReleaseYear,Price,Rated,Genre,Plot,Poster,ImdbRating,ImdbID")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Search(string query)
        {
            var movieSearch = await _movieAccess.SearchMovies(query);
            return View(movieSearch);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieStore.Web/Views/Shared/_CustomerDetailsPartial.cshtml
@model MovieStore.Web.Models.CustomerDetailsCheckOutViewModel

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Personal details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingCity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingCity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingZip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingZip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingZip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryCity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryCity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryCity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryZip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryZip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryZip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Proceed to payment" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

MovieStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LMDb</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body class="bg-dark">
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
        @*@Html.ActionLink("Movie Store", "Index", "Home", new { }, new { @class = "navbar-brand text-warning" })*@
        <a href="@Url.Action("Index", "Home")" class="navbar-brand text-warning">
            <img src="~/Content/Images/logo.svg" width="50" height="30" class="d-inline-block align-top" alt="" loading="lazy">
        </a>
        <button class="navbar-toggler text-warning border-warning py-2" onclick="javascript:$('#hamburger').toggleClass('rotated')" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            @*<span class="navbar-toggler-icon"></span>*@
            <i class="fas fa-bars hamburger" id="hamburger"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link text-light" })</li>
                <li class="nav-item">@Html.ActionLink("Top 100", "Top100", "Home", new { }, new { @class = "nav-link text-light text-nowrap" })</li>
            </ul>
            @using (Html.BeginForm("Search", "Movies", FormMethod.Post, new { @class = "form-inline my-2 my-lg-0 mr-2 flex w-100 mx-2" }))
            {
                @Html.AntiForgeryToken()
                <input name="query" style="max-width: none;" class="form-control mr-sm-2 d-block flex-grow-1 flex-fill" type="search" placeholder="Search Movies" aria-label="Search">
                <button class="btn btn-warning my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
            }

            @Html.Partial("_ShopingCartPartial")
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="body-content container">
        <div class="alert alert-warning bg-warning border-0 text-dark cart-alert" style="display: none; opacity: 0;" role="alert">
            Added! <br />
            @Html.ActionLink("Go to checkout.", "Index", "Cart", null, new { @class = " text-dark" })
        </div>

        @RenderBody()

        <footer>
            <div class="d-flex flex-row align-items-center justify-content-center">
                <p class="text-warning m-0">&copy; @DateTime.Now.Year - LMDb</p>
                @Html.ActionLink("About", "About", "Home", new { }, new { @class = "nav-link text-warning ml-3" })
                @Html.ActionLink("Contact", "Contact", "Home", new { }, new { @class = "nav-link text-warning" })
            </div>
        </footer>
    </div>

    <script src="https://kit.fontawesome.com/b99a277209.js" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

MovieStore.Web/Views/Shared/_MovieCartPartial.cshtml
@model MovieStore.Web.Models.MovieCartPartialViewModel

<div class="col-12 col-md-6 d-flex mb-4 bg-secondary pl-0">
    <img class="img-fluid" style="max-width: 30%; height: auto;" src="@Model.Movie.Poster" alt="Card image cap">
    <div class="ml-4">
        <h3 class="text-warning">@Model.Movie.Title</h3>
        <h6 class="text-secondary">Price:<span class="text-light"> @Model.Movie.Price </span></h6>
        <h6 class="text-secondary">Amount:<span class="text-light"> @Model.Count </span></h6>
        <h6 class="text-secondary">Total:<span class="text-light"> @Model.TotalPrice </span></h6>
    </div>
    <div class="ml-auto align-self-center">
        <a href="@Url.Action("Remove", new { movieId = Model.Movie.Id })" class="mx-2 text-danger"><i class="fas fa-minus fa-2x"></i></a>
        <a href="@Url.Action("Add", new { movieId = Model.Movie.Id })" class="mx-2 text-success"><i class="fas fa-plus fa-2x"></i></a>
    </div>
</div>

@*<div style="padding-bottom: 1px; background-color: #ffc107; margin-bottom: 1.5rem"></div>*@

MovieStore.Web/Views/Shared/_MovieCheckOutPartial.cshtml
@model MovieStore.Web.Models.MovieCartPartialViewModel

<div class="col-12 col-md-6 d-flex mb-4 bg-secondary pl-0">
    <img class="img-fluid" style="max-width: 30%; height: auto;" src="@Model.Movie.Poster" alt="Card image cap">
    <div class="ml-4">
        <h3 class="text-warning">@Model.Movie.Title</h3>
        <h6 class="text-secondary">Price:<span class="text-light"> @Model.Movie.Price </span></h6>
        <h6 class="text-secondary">Amount:<span class="text-light"> @Model.Count </span></h6>
        <h6 class="text-secondary">Total:<span class="text-light"> @Model.TotalPrice </span></h6>
    </div>
</div>

MovieStore.Web/Views/Shared/_MoviePartial.cshtml
@model MovieStore.Lib.Models.Movie

<div class="card bg-secondary text-light col-lg-3 col-md-4 col-sm-6 my-4 pt-4 pb-1 mx-2" style="min-width: 30%;">
    <img class="card-img-top img-fluid" src="@Model.Poster" alt="Card image cap" loading="lazy">
    <div class="card-body">
        <h5 class="card-title">@Model.Title <span class="badge badge-dark" style="color: #e0e0e0;">@Model.ReleaseYear</span></h5>
        <h6 class="card-subtitle mb-2 text-muted">IMDb Rating <span class="badge badge-warning">@Model.ImdbRating</span></h6>
        <p class="card-text">
            @if (Model.Plot.Length > 150)
            {
                <span>
                    @Model.Plot.Substring(0, 150)...
                </span>
                <span class="badge badge-pill badge-secondary" style="color: #e0e0e0;">
                    @Html.ActionLink("Read More", "Details", "Movies", new { id = Model.Id }, new { @class = "text-decoration-none text-light" })
                </span>
            }
            else
            {
                @Model.Plot
            }
        </p>
        <h6 class="card-subtitle mb-2 text-muted">Genres: <span class="badge badge-warning">@Model.Genre</span></h6>
        <h6 class="card-subtitle mb-2 text-muted">Rated: <span class="badge badge-warning">@Model.Rated</span></h6>
    </div>
    <h5 class="card-subtitle text-center text-warning mb-4 d-block"><span class="d-block badge badge-pill badge-dark" style="color: #e0e0e0;">@Model.Price :-</span></h5>
    @using (Html.BeginForm("AddToCart", "Cart", FormMethod.Post, new { id = "addToCartForm" + Model.Id, @class = "navbar-nav navbar-right" }))
    {
        @Html.AntiForgeryToken()
        <input name="movieId" type="hidden" value="@Model.Id" />

        <div class="card-footer bg-secondary pt-3">
            <a tabindex="0" id="addToCartSubmit@(Model.Id)" class="btn btn-outline-warning float-left addToCartBtn" data-placement="top" role="button" data-toggle="popover" data-trigger="focus" data-content="Added to cart!">Add to cart</a>
            @Html.ActionLink("Details", "Details", "Movies", new { id = Model.Id }, new { @class = "btn btn-outline-warning float-right" })
        </div>

    }
</div>

<style>
    .popover {
        background: #ffc107;
        border: solid 5px #ffc107;
    }
</style>

<script>
    $(function () {
        $(".cart-alert").hide();
        $('#addToCartSubmit@(Model.Id)').click(async function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddToCart", "Cart")',
                data: {
                    __RequestVerificationToken: document.getElementsByName("__RequestVerificationToken")[0].value,
                    movieId: @Model.Id
                },
                success: function(res) {
                    console.log(res);
                    $("#cartAmount").text(res);
                }
            });

            $(".fa-shopping-cart").toggleClass("animate");
            setTimeout(function () {
                $(".fa-shopping-cart").toggleClass("animate");
            }, 500);

            $(".cart-alert").show().animate({ opacity: 1 }, 250);
            await setTimeout(function () {
                $(".cart-alert").animate({ opacity: 0 }, 250).hide();
            }, 4000)
            return false;
        });
    })
</script>

MovieStore.Web/Views/Shared/_MovieSearchPartial.cshtml
@model MovieStore.Lib.Models.MovieSearchObjectResponse

<div class="col-12 col-md-6 d-flex mb-4 bg-secondary pl-0">
    <img class="img-fluid" style="max-width: 40%; height: auto;" src="@Model.Poster" alt="Card image cap" onerror="this.onerror = null; this.src = '@Url.Content("~/Content/Images/image-icon.svg")'; this.style.maxWidth = '20%';this.style.margin = '0 2.5rem'">
    <div class="ml-4 mt-3 col-6">
        <p class="badge badge-pill badge-secondary w-100">@string.Format("{0}{1}", Model.Type[0].ToString().ToUpper(), Model.Type.Substring(1))</p>
        <h5 class="text-center mt-4 mb-0 text-wrap">@Model.Title</h5>
        <h6 class="text-center mb-4"><span class="badge badge-pill badge-warning mt-2">@Model.Year</span></h6>
        @Html.ActionLink("Details", "DetailsImdb", "Movies", new { id = Model.imdbID }, new { @class = "btn btn-outline-warning d-block mb-2 mx-auto" })
    </div>
</div>

MovieStore.Web/Views/Shared/_ShopingCartPartial.cshtml
<ul class="navbar-nav navbar-right navbar-light bg-secondary mr-2">
    <li class="nav-item">
        <a href="@Url.Action("Index", "Cart")" id="cartBtn" class="btn py-0 px-1 text-info text-nowrap" style="font-size: 1.75rem;">
            <i class="fas fa-shopping-cart"></i>

            @if (((List<MovieStore.Lib.Models.Movie>)Session["CartMovies"]) == null)
            {
                <span id="cartAmount"></span>
            }
            else
            {
                <span id="cartAmount">@(((List<MovieStore.Lib.Models.Movie>)Session["CartMovies"]).Count)</span>
            }
        </a>
    </li>
</ul>

MovieStore.Web/Views/Shared/_Top100MoviePartial.cshtml
@model MovieStore.Lib.Models.Movie

<div class="card bg-secondary text-light col-12 col-lg-2 col-md-3 col-sm-4 my-4 py-4 px-2 mx-1" style="min-width: 15%;">
    <img class="card-img-top img-fluid rounded-0" src="@Model.Poster" alt="Card image cap" loading="lazy">
    <h5 class="card-subtitle text-center text-warning d-block mb-1"><span class="d-block badge rounded-0 badge-dark px-2"><i class="fas fa-star mr-1 text-warning" style="padding: 0.2rem 0rem;"></i>@Model.ImdbRating <small class="text-secondary">/ 10</small></span></h5>
    <h5 class="card-subtitle text-center text-warning d-block"><span class="d-block badge rounded-0 badge-dark px-2 text-warning border-top border-secondary" style="color: #e0e0e0; padding: 0.35rem 0rem;">@Model.Price :-</span></h5>
    @using (Html.BeginForm("AddToCart", "Cart", FormMethod.Post, new { id = "addToCartForm" + Model.Id, @class = "navbar-nav navbar-right d-flex flex-row justify-content-center" }))
    {
        <a tabindex="0" id="addToCartSubmit@(Model.Id)" class="w-50 btn border-right-0 btn-outline-warning rounded-0 float-left addToCartBtn py-1" data-placement="top" role="button" data-toggle="popover" data-trigger="focus" data-content="Added to cart!"><i class="fas fa-cart-plus"></i></a>
        <a href="@Url.Action("Details", "Movies", new { id = Model.Id })" class="w-50 btn rounded-0 btn-outline-warning float-right py-1"><i class="fas fa-info"></i></a>

        @Html.AntiForgeryToken()
        <input name="movieId" type="hidden" value="@Model.Id" />
    }
    @*<div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <h6 class="card-subtitle mb-2 text-muted">IMDb Rating <span class="badge badge-warning">@Model.ImdbRating</span></h6>
        </div>*@
    @*@using (Html.BeginForm("AddToCart", "Cart", FormMethod.Post, new { id = "addToCartForm" + Model.Id, @class = "navbar-nav navbar-right" }))
        {
            @Html.AntiForgeryToken()
            <input name="movieId" type="hidden" value="@Model.Id" />

            <div class="card-footer bg-secondary d-flex flex-column">
                <a tabindex="0" id="addToCartSubmit@(Model.Id)" class="btn btn-outline-warning float-left addToCartBtn mb-3 py-1" data-placement="top" role="button" data-toggle="popover" data-trigger="focus" data-content="Added to cart!">Add to cart</a>
                @Html.ActionLink("Details", "Details", "Movies", new { id = Model.Id }, new { @class = "btn btn-outline-warning float-right py-1" })
            </div>

        }*@
</div>

<style>
    .popover {
        background: #ffc107;
        border: solid 5px #ffc107;
    }
</style>

<script>
    $(function () {
        $(".cart-alert").hide();
        $('#addToCartSubmit@(Model.Id)').click(async function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddToCart", "Cart")',
                data: {
                    __RequestVerificationToken: document.getElementsByName("__RequestVerificationToken")[0].value,
                    movieId: @Model.Id
                },
                success: function(res) {
                    console.log(res);
                    $("#cartAmount").text(res);
                }
            });

            $(".fa-shopping-cart").toggleClass("animate");
            setTimeout(function () {
                $(".fa-shopping-cart").toggleClass("animate");
            }, 500);

            $(".cart-alert").show().animate({ opacity: 1 }, 250);
            await setTimeout(function () {
                $(".cart-alert").animate({ opacity: 0 }, 250).hide();
            }, 4000)
            return false;
        });
    })
</script>